CREATE TABLE companies (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  name VARCHAR(256) NOT NULL,
  document VARCHAR(256) NOT NULL,
  createdAt TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deletedAt TIMESTAMP(3)
);

CREATE TABLE users (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  name VARCHAR(256) NOT NULL,
  email VARCHAR(256) NOT NULL,
  password VARCHAR(256) NOT NULL,
  createdAt TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deletedAt TIMESTAMP(3),
  companyId VARCHAR(39) NOT NULL REFERENCES companies(id)
);

CREATE TABLE catalog_databases (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  name VARCHAR(256) NOT NULL,
  description TEXT NOT NULL,
  createdBy VARCHAR(256) NOT NULL,
  createdAt TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deletedAt TIMESTAMP(3),
  companyId VARCHAR(39) NOT NULL REFERENCES companies(id)
);

CREATE TABLE catalog_tables (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  name VARCHAR(256) NOT NULL,
  description TEXT NOT NULL,
  schema VARCHAR(256) NOT NULL,
  createdAt TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deletedAt TIMESTAMP(3),
  databaseId VARCHAR(39) NOT NULL REFERENCES catalog_databases(id)
);